version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql
      - ./docker/mariadb-seed.sql:/docker-entrypoint-initdb.d/mariadb-seed.sql

volumes:
  mariadb_data:
