INSERT INTO Product (Name, Description, ProductType, PriceType, Code, Price, IsPrimary, S3Url) VALUES

-- 'Seeding Suit Data' AS log_message;
('TheAristocrat', 'Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheAristocrat/Image_001.JPG'),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheAristocrat/Image_002.JPG'),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheAristocrat/Image_003.JPG'),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheAristocrat/Image_004.JPG'),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheAristocrat/Image_005.JPG'),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheAristocrat/Image_006.JPG'),
('TheClassicVirtuoso', 'Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheClassicVirtuoso/Image_001.JPG'),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheClassicVirtuoso/Image_002.JPG'),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheClassicVirtuoso/Image_003.JPG'),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheClassicVirtuoso/Image_004.JPG'),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheClassicVirtuoso/Image_005.JPG'),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheClassicVirtuoso/Image_006.JPG'),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheClassicVirtuoso/Image_007.JPG'),
('TheCosmopolitan', 'Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_001.JPG'),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_002.JPG'),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_003.JPG'),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_004.JPG'),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_005.JPG'),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_006.JPG'),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_007.JPG'),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheCosmopolitan/Image_008.JPG'),
('TheLuminary', 'Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheLuminary/Image_001.JPG'),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheLuminary/Image_002.JPG'),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheLuminary/Image_003.JPG'),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheLuminary/Image_004.JPG'),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheLuminary/Image_005.JPG'),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheLuminary/Image_006.JPG'),
('TheMaverick', 'Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheMaverick/Image_001.JPG'),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheMaverick/Image_002.JPG'),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheMaverick/Image_003.JPG'),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheMaverick/Image_004.JPG'),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheMaverick/Image_005.JPG'),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheMaverick/Image_006.JPG'),
('TheNobleSovereign', 'Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheNobleSovereign/Image_001.JPG'),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheNobleSovereign/Image_002.JPG'),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheNobleSovereign/Image_003.JPG'),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheNobleSovereign/Image_004.JPG'),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheNobleSovereign/Image_005.JPG'),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheNobleSovereign/Image_006.JPG'),
('TheVanguard', 'Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheVanguard/Image_001.JPG'),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheVanguard/Image_002.JPG'),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheVanguard/Image_003.JPG'),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheVanguard/Image_004.JPG'),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheVanguard/Image_005.JPG'),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheVanguard/Image_006.JPG'),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, 'https://d167viv9yasg8.cloudfront.net/DesignOfSuit/TheVanguard/Image_007.JPG'),


-- 'Seeding Fabric Data' AS log_message;
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_001.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_002.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_003.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_004.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_005.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_006.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_007.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_008.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_009.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_010.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_011.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_012.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_013.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_014.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_015.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_016.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_017.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_018.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_019.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_020.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_021.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_022.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_023.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_024.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_025.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_026.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_027.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_028.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_029.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_030.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_031.png'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_001.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_002.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_003.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_004.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_005.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_006.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_007.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_008.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_009.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_010.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_011.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_012.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_013.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_014.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_015.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_016.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_017.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_018.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_019.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_020.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_021.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_022.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_023.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_024.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_025.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_026.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_027.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_028.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_029.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_030.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_031.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_032.jpg'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_033.jpg'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_001.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_002.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_003.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_004.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_005.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_006.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_007.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_008.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_009.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_010.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_011.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_012.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_013.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_001.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_002.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_003.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_004.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_005.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_006.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_007.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_008.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_009.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_010.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_011.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_012.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_013.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_015.png'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_001.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_002.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_003.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_004.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_005.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_006.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_007.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_008.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_009.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_010.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_011.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_012.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_013.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_014.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_015.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_016.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_017.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_018.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_019.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_020.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_021.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_022.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_023.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_024.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_025.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_026.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_027.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_028.JPG'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_001.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_002.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_003.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_004.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_005.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_006.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_007.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_008.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_009.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_010.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_011.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_012.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_013.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_014.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_015.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_016.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_017.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_018.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_019.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_020.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_021.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_022.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_023.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_024.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_025.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_026.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_027.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_028.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_029.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_030.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_031.png'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_001.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_002.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_003.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_004.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_005.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_006.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_007.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_008.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_009.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_010.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_011.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_012.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_013.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_014.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_015.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_016.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_017.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_018.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_019.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_020.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_021.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_022.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_023.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_024.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_025.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_026.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_027.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_028.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_029.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_030.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_031.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_032.jpg'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_033.jpg'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_001.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_002.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_003.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_004.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_005.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_006.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_007.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_008.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_009.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_010.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_011.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_012.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_013.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_001.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_002.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_003.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_004.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_005.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_006.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_007.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_008.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_009.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_010.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_011.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_012.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_013.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_015.png'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_001.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_002.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_003.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_004.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_005.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_006.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_007.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_008.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_009.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_010.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_011.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_012.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_013.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_014.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_015.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_016.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_017.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_018.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_019.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_020.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_021.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_022.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_023.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_024.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_025.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_026.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_027.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_028.JPG'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_001.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_002.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_003.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_004.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_005.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_006.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_007.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_008.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_009.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_010.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_011.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_012.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_013.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_014.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_015.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_016.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_017.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_018.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_019.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_020.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_021.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_022.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_023.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_024.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_025.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_026.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_027.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_028.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_029.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_030.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_031.png'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_001.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_002.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_003.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_004.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_005.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_006.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_007.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_008.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_009.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_010.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_011.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_012.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_013.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_014.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_015.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_016.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_017.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_018.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_019.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_020.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_021.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_022.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_023.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_024.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_025.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_026.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_027.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_028.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_029.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_030.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_031.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_032.jpg'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_033.jpg'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_001.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_002.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_003.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_004.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_005.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_006.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_007.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_008.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_009.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_010.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_011.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_012.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_013.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_001.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_002.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_003.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_004.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_005.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_006.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_007.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_008.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_009.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_010.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_011.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_012.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_013.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_015.png'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_001.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_002.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_003.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_004.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_005.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_006.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_007.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_008.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_009.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_010.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_011.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_012.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_013.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_014.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_015.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_016.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_017.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_018.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_019.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_020.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_021.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_022.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_023.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_024.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_025.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_026.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_027.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_028.JPG'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_001.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_002.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_003.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_004.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_005.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_006.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_007.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_008.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_009.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_010.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_011.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_012.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_013.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_014.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_015.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_016.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_017.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_018.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_019.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_020.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_021.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_022.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_023.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_024.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_025.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_026.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_027.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_028.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_029.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_030.png'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/CashmereBlend/Image_031.png'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_001.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_002.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_003.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_004.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_005.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_006.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_007.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_008.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_009.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_010.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_011.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_012.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_013.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_014.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_015.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_016.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_017.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_018.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_019.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_020.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_021.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_022.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_023.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_024.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_025.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_026.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_027.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_028.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_029.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_030.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_031.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_032.jpg'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Linen/Image_033.jpg'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_001.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_002.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_003.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_004.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_005.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_006.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_007.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_008.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_009.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_010.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_011.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_012.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_013.png'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/MerinoWoolBlend/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_001.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_002.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_003.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_004.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_005.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_006.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_007.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_008.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_009.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_010.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_011.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_012.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_013.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_014.png'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/Super150sWool/Image_015.png'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_001.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_002.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_003.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_004.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_005.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_006.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_007.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_008.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_009.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_010.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_011.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_012.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_013.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_014.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_015.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_016.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_017.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_018.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_019.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_020.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_021.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_022.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_023.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_024.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_025.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_026.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_027.JPG'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'https://d167viv9yasg8.cloudfront.net/FabricOptions/WoolAndVlvet/Image_028.JPG'), 


-- 'Seeding Suit Type Data' AS log_message;
('ThreePieceSuit', NULL, 'SuitType', 'ThreePieceSuit', NULL, 0, 100, 'https://d167viv9yasg8.cloudfront.net/SuitType/ThreePieceSuit/Image_001.JPG'),
('ThreePieceSuit', NULL, 'SuitType', 'ThreePieceSuit', NULL, 0, 100, 'https://d167viv9yasg8.cloudfront.net/SuitType/ThreePieceSuit/Image_002.JPG'),
('ThreePieceSuit', NULL, 'SuitType', 'ThreePieceSuit', NULL, 0, 100, 'https://d167viv9yasg8.cloudfront.net/SuitType/ThreePieceSuit/Image_003.JPG'),
('TwoPieceSuit', NULL, 'SuitType', 'TwoPieceSuit', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/SuitType/TwoPieceSuit/Image_001.JPG'),
('TwoPieceSuit', NULL, 'SuitType', 'TwoPieceSuit', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/SuitType/TwoPieceSuit/Image_002.JPG'),
('TwoPieceSuit', NULL, 'SuitType', 'TwoPieceSuit', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/SuitType/TwoPieceSuit/Image_003.JPG'),


-- 'Seeding Lining Data' AS log_message;
('Image_001.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_001.png'),
('Image_002.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_002.png'),
('Image_003.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_003.png'),
('Image_004.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_004.png'),
('Image_005.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_005.png'),
('Image_006.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_006.png'),
('Image_007.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_007.png'),
('Image_008.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_008.png'),
('Image_009.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_009.png'),
('Image_010.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_010.png'),
('Image_011.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_011.png'),
('Image_012.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_012.png'),
('Image_013.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_013.png'),
('Image_014.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_014.png'),
('Image_015.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_015.png'),
('Image_016.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_016.png'),
('Image_017.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_017.png'),
('Image_018.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_018.png'),
('Image_019.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_019.png'),
('Image_020.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_020.png'),
('Image_021.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_021.png'),
('Image_022.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_022.png'),
('Image_023.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_023.png'),
('Image_024.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_024.png'),
('Image_025.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_025.png'),
('Image_026.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_026.png'),
('Image_027.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_027.png'),
('Image_028.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_028.png'),
('Image_029.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_029.png'),
('Image_030.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_030.png'),
('Image_031.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_031.png'),
('Image_032.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_032.png'),
('Image_033.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_033.png'),
('Image_034.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_034.png'),
('Image_035.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_035.png'),
('Image_036.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_036.png'),
('Image_037.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_037.png'),
('Image_038.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_038.png'),
('Image_039.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_039.png'),
('Image_040.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_040.png'),
('Image_041.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_041.png'),
('Image_042.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_042.png'),
('Image_043.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_043.png'),
('Image_044.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_044.png'),
('Image_045.png', NULL, 'Lining', 'Lining', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Lining/Image_045.png'),


-- 'Seeding Button Data' AS log_message;
('Image_001.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_001.JPG'),
('Image_002.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_002.JPG'),
('Image_003.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_003.JPG'),
('Image_004.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_004.JPG'),
('Image_005.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_005.JPG'),
('Image_006.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_006.JPG'),
('Image_007.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_007.JPG'),
('Image_008.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_008.JPG'),
('Image_009.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_009.JPG'),
('Image_010.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_010.JPG'),
('Image_011.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_011.JPG'),
('Image_012.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_012.JPG'),
('Image_013.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_013.JPG'),
('Image_014.JPG', NULL, 'Button', 'Button', NULL, 0, 0, 'https://d167viv9yasg8.cloudfront.net/Buttons/Image_014.JPG');