INSERT INTO Product (Name, Description, ProductType, PriceType, Code, Price, IsPrimary, S3Url) VALUES

-- 'Seeding Suit Data' AS log_message;
('TheAristocrat', 'Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, ''),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheAristocrat','Effortlessly blending heritage and modernity', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheClassicVirtuoso', 'Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, ''),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheClassicVirtuoso','Timeless elegance with a contemporary twist', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheCosmopolitan', 'Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, ''),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheCosmopolitan','Refined simplicity for global professionals', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheLuminary', 'Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, ''),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheLuminary','Radiating confidence and distinction for trailblazers', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheMaverick', 'Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, ''),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheMaverick','Unique cuts and textures for the daring individual', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheNobleSovereign', 'Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, ''),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheNobleSovereign','Sophistication tailored for formal excellence', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheVanguard', 'Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 1, ''),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),
('TheVanguard','Bold, modern, and sharp for industry leaders', 'DesignOfSuit', 'FullSuit', NULL, 500, 0, ''),


-- 'Seeding Fabric Data' AS log_message;
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'D725'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'K725'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'C725'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'B509'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'C509'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'A509'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'B476'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'C476'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'D502'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'A502'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'B502'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'A476'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-160#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-161#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-162#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-166#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-165#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-163#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-10#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-9#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-8#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-13#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-12#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-11#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-15#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'SUNSHINE-270-14#'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'K728'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'A728'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'D728'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'C728'), 
('CashmereBlend', NULL, 'FabricOptions', 'JacketOnlyCashmereWool', '', 500, 0, 'B728'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'BEDA_M102_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'BEDA_M106_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'BEDO_M100_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'BEHONGNHAT_M103_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'DO_M105_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'GACH_UOT_M139_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'GACH_M136_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'INDIGO_M146_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'INDIGO_M77_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'KEM_M101_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'KEM_M104_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'KEM_M151_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'KEM_M154_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'MAUBO_M156_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'METALGREY_M137_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'NAUGO_M144_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'NAUHATOCCHO_M134_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'REUNHAT_M153_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'REU_M155_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'TIMANHXANH_M122_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XAMCHIANHNAU_M117_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XAMCHI_M159_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XAMXANH_M118_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHBIENNHAT_M116_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XAMCHAM_M147_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHCOVITDAM_M119_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHDA_M124_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHDA_M161_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHDAUNHAT_M150_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHNGODAM_M162_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHREU_M145_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANHREU_M152_200GSM'), 
('Linen', NULL, 'FabricOptions', 'JacketOnlyLinen200GSM', '', 550, 0, 'XANH_M120_200GSM'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-8'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-15'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-14'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-13'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-17'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-3'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-2'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-16'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-10'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-7'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-1'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-6'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-5'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'JacketOnlyMerinoWool', '', 600, 0, 'DT789-9'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB322'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB11'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB12'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB13'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB312'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB320'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB321'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FBW8'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB1'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB3'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB5'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB6'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB7'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB9'), 
('Super150Wool', NULL, 'FabricOptions', 'JacketOnlySuperWool150', '', 400, 0, 'FWB10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-01'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-11'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-12'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-13'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-14'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-15'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-16'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-17'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-18'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-19'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-02'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-20'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-21'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-22'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-23'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-24'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-25'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-26'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-27'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-28'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-03'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-04'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-05'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-06'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-07'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-08'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'JacketOnlyVelvette', '', 450, 0, 'VP-09'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'D725'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'K725'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'C725'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'B509'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'C509'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'A509'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'B476'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'C476'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'D502'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'A502'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'B502'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'A476'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-160#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-161#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-162#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-166#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-165#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-163#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-10#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-9#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-8#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-13#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-12#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-11#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-15#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'SUNSHINE-270-14#'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'K728'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'A728'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'D728'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'C728'), 
('CashmereBlend', NULL, 'FabricOptions', 'VestCoatOnlyCashmereWool', '', 200, 0, 'B728'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'BEDA_M102_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'BEDA_M106_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'BEDO_M100_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'BEHONGNHAT_M103_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'DO_M105_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'GACH_UOT_M139_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'GACH_M136_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'INDIGO_M146_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'INDIGO_M77_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'KEM_M101_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'KEM_M104_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'KEM_M151_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'KEM_M154_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'MAUBO_M156_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'METALGREY_M137_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'NAUGO_M144_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'NAUHATOCCHO_M134_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'REUNHAT_M153_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'REU_M155_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'TIMANHXANH_M122_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XAMCHIANHNAU_M117_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XAMCHI_M159_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XAMXANH_M118_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHBIENNHAT_M116_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XAMCHAM_M147_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHCOVITDAM_M119_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHDA_M124_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHDA_M161_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHDAUNHAT_M150_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHNGODAM_M162_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHREU_M145_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANHREU_M152_200GSM'), 
('Linen', NULL, 'FabricOptions', 'VestCoatOnlyLinen200GSM', '', 225, 0, 'XANH_M120_200GSM'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-8'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-15'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-14'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-13'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-17'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-3'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-2'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-16'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-10'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-7'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-1'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-6'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-5'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'VestCoatOnlyMerinoWool', '', 250, 0, 'DT789-9'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB322'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB11'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB12'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB13'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB312'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB320'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB321'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FBW8'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB1'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB3'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB5'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB6'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB7'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB9'), 
('Super150Wool', NULL, 'FabricOptions', 'VestCoatOnlySuperWool150', '', 150, 0, 'FWB10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-01'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-11'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-12'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-13'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-14'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-15'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-16'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-17'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-18'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-19'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-02'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-20'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-21'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-22'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-23'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-24'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-25'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-26'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-27'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-28'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-03'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-04'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-05'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-06'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-07'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-08'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'VestCoatOnlyVelvette', '', 175, 0, 'VP-09'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'D725'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'K725'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'C725'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'B509'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'C509'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'A509'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'B476'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'C476'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'D502'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'A502'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'B502'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'A476'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-160#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-161#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-162#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-166#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-165#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-163#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-10#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-9#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-8#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-13#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-12#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-11#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-15#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'SUNSHINE-270-14#'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'K728'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'A728'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'D728'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'C728'), 
('CashmereBlend', NULL, 'FabricOptions', 'TrouserOnlyCashmereBlend', '', 180, 0, 'B728'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'BEDA_M102_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'BEDA_M106_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'BEDO_M100_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'BEHONGNHAT_M103_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'DO_M105_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'GACH_UOT_M139_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'GACH_M136_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'INDIGO_M146_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'INDIGO_M77_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'KEM_M101_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'KEM_M104_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'KEM_M151_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'KEM_M154_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'MAUBO_M156_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'METALGREY_M137_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'NAUGO_M144_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'NAUHATOCCHO_M134_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'REUNHAT_M153_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'REU_M155_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'TIMANHXANH_M122_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XAMCHIANHNAU_M117_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XAMCHI_M159_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XAMXANH_M118_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHBIENNHAT_M116_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XAMCHAM_M147_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHCOVITDAM_M119_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHDA_M124_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHDA_M161_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHDAUNHAT_M150_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHNGODAM_M162_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHREU_M145_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANHREU_M152_200GSM'), 
('Linen', NULL, 'FabricOptions', 'TrouserOnlyLinen200GSM', '', 200, 0, 'XANH_M120_200GSM'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-8'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-15'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-14'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-13'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-17'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-3'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-2'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-16'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-10'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-7'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-1'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-6'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-5'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'TrouserOnlyMerinoWool', '', 220, 0, 'DT789-9'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB322'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB11'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB12'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB13'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB312'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB320'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB321'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FBW8'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB1'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB3'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB5'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB6'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB7'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB9'), 
('Super150Wool', NULL, 'FabricOptions', 'TrouserOnlySuperWool150', '', 140, 0, 'FWB10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-01'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-11'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-12'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-13'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-14'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-15'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-16'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-17'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-18'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-19'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-02'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-20'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-21'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-22'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-23'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-24'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-25'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-26'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-27'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-28'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-03'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-04'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-05'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-06'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-07'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-08'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'TrouserOnlyVelvette', '', 160, 0, 'VP-09'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'D725'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'K725'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'C725'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'B509'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'C509'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'A509'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'B476'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'C476'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'D502'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'A502'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'B502'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'A476'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-160#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-161#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-162#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-166#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-165#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-163#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-10#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-9#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-8#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-13#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-12#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-11#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-15#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'SUNSHINE-270-14#'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'K728'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'A728'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'D728'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'C728'), 
('CashmereBlend', NULL, 'FabricOptions', 'FullSuitCashmereWool', '', 150, 0, 'B728'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'BEDA_M102_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'BEDA_M106_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'BEDO_M100_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'BEHONGNHAT_M103_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'DO_M105_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'GACH_UOT_M139_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'GACH_M136_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'INDIGO_M146_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'INDIGO_M77_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'KEM_M101_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'KEM_M104_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'KEM_M151_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'KEM_M154_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'MAUBO_M156_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'METALGREY_M137_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'NAUGO_M144_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'NAUHATOCCHO_M134_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'REUNHAT_M153_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'REU_M155_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'TIMANHXANH_M122_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XAMCHIANHNAU_M117_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XAMCHI_M159_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XAMXANH_M118_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHBIENNHAT_M116_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XAMCHAM_M147_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHCOVITDAM_M119_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHDA_M124_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHDA_M161_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHDAUNHAT_M150_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHNGODAM_M162_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHREU_M145_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANHREU_M152_200GSM'), 
('Linen', NULL, 'FabricOptions', 'FullSuitLinen200GSM', '', 200, 0, 'XANH_M120_200GSM'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-8'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-15'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-14'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-13'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-17'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-3'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-2'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-16'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-10'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-7'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-1'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-6'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-5'), 
('MerinoWoolBlend', NULL, 'FabricOptions', 'FullSuitMerinoWool', '', 275, 0, 'DT789-9'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB322'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB11'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB12'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB13'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB312'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB320'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB321'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FBW8'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB1'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB3'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB5'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB6'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB7'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB9'), 
('Super150Wool', NULL, 'FabricOptions', 'FullSuitSuperWool150', '', 0, 0, 'FWB10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-01'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-10'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-11'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-12'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-13'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-14'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-15'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-16'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-17'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-18'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-19'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-02'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-20'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-21'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-22'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-23'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-24'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-25'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-26'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-27'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-28'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-03'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-04'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-05'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-06'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-07'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-08'), 
('WoolAndVlvet', NULL, 'FabricOptions', 'FullSuitVelvette', '', 75, 0, 'VP-09'), 


-- 'Seeding Suit Type Data' AS log_message;
('ThreePieceSuit', NULL, 'SuitType', 'ThreePieceSuit', NULL, 0, 100, ''),
('ThreePieceSuit', NULL, 'SuitType', 'ThreePieceSuit', NULL, 0, 100, ''),
('ThreePieceSuit', NULL, 'SuitType', 'ThreePieceSuit', NULL, 0, 100, ''),
('TwoPieceSuit', NULL, 'SuitType', 'TwoPieceSuit', NULL, 0, 0, ''),
('TwoPieceSuit', NULL, 'SuitType', 'TwoPieceSuit', NULL, 0, 0, ''),
('TwoPieceSuit', NULL, 'SuitType', 'TwoPieceSuit', NULL, 0, 0, ''),


-- 'Seeding Lining Data' AS log_message;
('Image_001.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_002.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_003.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_004.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_005.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_006.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_007.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_008.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_009.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_010.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_011.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_012.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_013.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_014.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_015.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_016.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_017.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_018.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_019.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_020.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_021.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_022.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_023.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_024.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_025.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_026.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_027.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_028.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_029.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_030.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_031.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_032.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_033.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_034.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_035.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_036.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_037.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_038.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_039.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_040.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_041.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_042.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_043.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_044.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),
('Image_045.png', NULL, 'Lining', 'Lining', NULL, 0, 0, ''),


-- 'Seeding Button Data' AS log_message;
('Image_001.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_002.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_003.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_004.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_005.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_006.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_007.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_008.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_009.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_010.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_011.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_012.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_013.JPG', NULL, 'Button', 'Button', NULL, 0, 0, ''),
('Image_014.JPG', NULL, 'Button', 'Button', NULL, 0, 0, '');

