name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          if [ -n "${{ secrets.EC2_HOST }}" ]; then
            echo "EC2_HOST is set"
          else
            echo "EC2_HOST is not set"
          fi
          if [ -n "${{ secrets.EC2_USER }}" ]; then
            echo "EC2_USER is set"
          else
            echo "EC2_USER is not set"
          fi
          if [ -n "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]; then
            echo "EC2_SSH_PRIVATE_KEY is set"
          else
            echo "EC2_SSH_PRIVATE_KEY is not set"
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/nextjs-mariadb-crud
            git pull origin master
            npm install
            npm run build
            pm2 restart nextjs-mariadb-crud 