name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "Checking EC2_HOST length: ${#EC2_HOST}"
          echo "Checking EC2_USER length: ${#EC2_USER}"
          echo "Checking EC2_SSH_PRIVATE_KEY length: ${#EC2_SSH_PRIVATE_KEY}"
          if [ -n "${{ secrets.EC2_HOST }}" ]; then
            echo "EC2_HOST is set and not empty"
          else
            echo "EC2_HOST is not set or empty"
          fi
          if [ -n "${{ secrets.EC2_USER }}" ]; then
            echo "EC2_USER is set and not empty"
          else
            echo "EC2_USER is not set or empty"
          fi
          if [ -n "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]; then
            echo "EC2_SSH_PRIVATE_KEY is set and not empty"
          else
            echo "EC2_SSH_PRIVATE_KEY is not set or empty"
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            cd /home/ubuntu/nextjs-mariadb-crud
            git pull origin master
            npm install
            npm run build
            pm2 restart nextjs-mariadb-crud 